name: Generate prebuilds for CI

on:
  push:
    branches: [main]

env:
  MODULE_NAME: "better-sqlite3"

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        target: ["android-arm", "android-arm64", "android-x64"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r24 # https://github.com/android/ndk/wiki/Unsupported-Downloads#r24
          add-to-path: false

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install
        run: npm ci

      - name: Generate prebuild for ${{ matrix.target }}
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        working-directory: ./node_modules/${{ env.MODULE_NAME }}
        run: npx prebuild-for-nodejs-mobile ${{ matrix.target }}

      - name: Upload prebuild artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./node_modules/${{ env.MODULE_NAME }}/prebuilds/${{ matrix.target }}
